# Generated by Django 4.2.7 on 2024-11-27 10:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('auction_type', models.CharField(choices=[('copart', 'Copart'), ('sublot_copart', 'Sublot Copart'), ('iaa', 'IAA'), ('sublot_iaa', 'Sublot IAA'), ('manheim', 'Manheim')], max_length=20, verbose_name='Тип аукциона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Аукцион',
                'verbose_name_plural': 'Аукционы',
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Порт',
                'verbose_name_plural': 'Порты',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('delivery_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость доставки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='calculator.auction', verbose_name='Аукцион')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculator.port', verbose_name='Порт')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'unique_together': {('auction', 'name')},
            },
        ),
    ]
