# Generated by Django 5.0.1 on 2024-02-01 13:28

import car_site.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_site', '0003_advuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsaPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=car_site.models.get_timestamp_path, verbose_name='Фото')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_site.usacard', verbose_name='Карточка США')),
            ],
            options={
                'verbose_name': 'Дополнительная материалы',
                'verbose_name_plural': 'Дополнительные материалы',
            },
        ),
    ]
