# Generated by Django 5.0.1 on 2024-02-01 17:50

import car_site.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_site', '0004_usaphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usaphoto',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.CreateModel(
            name='UsaPaymentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=car_site.models.get_file_path, verbose_name='Файл')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_site.usacard', verbose_name='Карточка США')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
