# Generated by Django 5.0.1 on 2024-02-02 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_site', '0005_alter_usaphoto_options_usapaymentfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usapaymentfile',
            options={'verbose_name': 'Файл оплаты', 'verbose_name_plural': 'Файлы оплаты'},
        ),
        migrations.AddField(
            model_name='usapaymentfile',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
