# Generated by Django 5.0.1 on 2024-02-02 14:36

import car_site.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_site', '0006_alter_usapaymentfile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EuropePaymentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=car_site.models.get_file_path, verbose_name='Файл')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_site.europecard', verbose_name='Карточка Европы')),
            ],
            options={
                'verbose_name': 'Файл оплаты',
                'verbose_name_plural': 'Файлы оплаты',
            },
        ),
        migrations.CreateModel(
            name='EuropePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=car_site.models.get_timestamp_path, verbose_name='Фото')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_site.europecard', verbose_name='Карточка Европы')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='KoreaPaymentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=car_site.models.get_file_path, verbose_name='Файл')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_site.koreacard', verbose_name='Карточка Южной Кореи')),
            ],
            options={
                'verbose_name': 'Файл оплаты',
                'verbose_name_plural': 'Файлы оплаты',
            },
        ),
        migrations.CreateModel(
            name='KoreaPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=car_site.models.get_timestamp_path, verbose_name='Фото')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_site.koreacard', verbose_name='Карточка Южной Кореи')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
