# Generated by Django 5.0.1 on 2024-02-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_site', '0008_userbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalance',
            name='description',
            field=models.CharField(default='test', max_length=1000, verbose_name='Комментарий'),
            preserve_default=False,
        ),
    ]
