# Generated by Django 5.0.1 on 2024-02-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_site', '0009_userbalance_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Баланс'),
        ),
    ]
