# Generated by Django 5.0.1 on 2024-02-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_site', '0012_alter_userbalance_date_created_usacustomdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usaextralink',
            name='name',
            field=models.CharField(default='Ссылка', max_length=300, verbose_name='Название'),
        ),
    ]
