# Generated by Django 5.0.1 on 2024-02-03 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_site', '0014_auction_alter_usacard_auction_platform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_site.auction', verbose_name='Аукцион')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_site.usacard', verbose_name='Карточка')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_site.platform', verbose_name='Площадка')),
            ],
        ),
    ]
