# Generated by Django 5.0.1 on 2024-02-04 10:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_site', '0015_auctiondata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllowedCombination',
            new_name='UsaAllowedCombination',
        ),
        migrations.RenameModel(
            old_name='Auction',
            new_name='UsaAuction',
        ),
        migrations.RenameModel(
            old_name='Platform',
            new_name='UsaPlatform',
        ),
        migrations.RemoveField(
            model_name='usacard',
            name='arrival_date_litva',
        ),
        migrations.RemoveField(
            model_name='usacard',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='usacard',
            name='car_sum',
        ),
        migrations.RemoveField(
            model_name='usacard',
            name='container_load_date',
        ),
        migrations.RemoveField(
            model_name='usacard',
            name='container_number',
        ),
        migrations.RemoveField(
            model_name='usacard',
            name='delivery_storage_date',
        ),
        migrations.RemoveField(
            model_name='usacard',
            name='lot_number',
        ),
        migrations.RemoveField(
            model_name='usacard',
            name='open_container_date',
        ),
        migrations.RemoveField(
            model_name='usacard',
            name='pay_date',
        ),
        migrations.RemoveField(
            model_name='usacard',
            name='payment_flag',
        ),
        migrations.RemoveField(
            model_name='usacard',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='usacard',
            name='port',
        ),
        migrations.AddField(
            model_name='auctiondata',
            name='container_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер контейнера'),
        ),
        migrations.AddField(
            model_name='auctiondata',
            name='lot_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер лота'),
        ),
        migrations.AddField(
            model_name='auctiondata',
            name='pay_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата покупки'),
        ),
        migrations.AddField(
            model_name='auctiondata',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название учетки'),
        ),
        migrations.AddField(
            model_name='usacard',
            name='age',
            field=models.CharField(choices=[('0-3 года', '0-3 года'), ('3-5 лет', '3-5 лет'), ('5-7 лет', '5-7 лет')], max_length=100, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='usacard',
            name='capacity',
            field=models.CharField(choices=[('1.0', '1.0'), ('1.1', '1.1'), ('1.2', '1.2'), ('1.3', '1.3'), ('1.4', '1.4'), ('1.5', '1.5'), ('1.6', '1.6'), ('1.7', '1.9'), ('2.0', '2.0'), ('2.2', '2.2'), ('2.3', '2.3'), ('2.4', '2.4'), ('2.5', '2.5'), ('2.8', '2.8'), ('2.9', '2.9'), ('3.0', '3.0'), ('3.2', '3.2'), ('3.5', '3.5'), ('3.6', '3.6'), ('4.0', '4.0'), ('4.2', '4.2'), ('4.4', '4.4'), ('5.0', '5.0'), ('5.3', '5.3'), ('5.4', '5.4'), ('5.5', '5.5'), ('5.7', '5.7'), ('6.0', '6.0'), ('6.2', '6.2'), ('6.3', '6.3'), ('6.4', '6.4')], max_length=100, null=True, verbose_name='Объем'),
        ),
        migrations.AddField(
            model_name='usacard',
            name='cnt_auto',
            field=models.CharField(choices=[('1 авто', '1 авто'), ('2 и более', '2 и более')], max_length=10, null=True, verbose_name='Кол-во авто, купленных за год'),
        ),
        migrations.AddField(
            model_name='usacard',
            name='engine_type',
            field=models.CharField(choices=[('Бензин / Дизель', 'Бензин / Дизель'), ('Гибрид', 'Гибрид'), ('Электро', 'Электро')], max_length=200, null=True, verbose_name='Тип двигателя'),
        ),
        migrations.AddField(
            model_name='usacard',
            name='massa',
            field=models.CharField(blank=True, choices=[('До  3,5 тонн', 'До  3,5 тонн'), ('Более 3,5 тонн', 'Более 3,5 тонн')], max_length=100, verbose_name='Масса техники (Пикап)'),
        ),
        migrations.AddField(
            model_name='usacard',
            name='motor_power',
            field=models.CharField(blank=True, choices=[('До 250-800 кубиков', 'До 250-800 кубиков'), ('Более 800 кубиков', 'Более 800 кубиков')], max_length=100, verbose_name='Объем двигателя (Мотоцикл)'),
        ),
        migrations.AddField(
            model_name='usacard',
            name='pending',
            field=models.BooleanField(default=False, verbose_name='Pending'),
        ),
        migrations.AddField(
            model_name='usacard',
            name='power',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Кол-во л. сил (Мотоцикл)'),
        ),
        migrations.AddField(
            model_name='usacard',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usacard',
            name='quadrupole',
            field=models.CharField(blank=True, choices=[('До 300 кубиков', 'До 300 кубиков'), ('Более 300 кубиков', 'Более 300 кубиков')], max_length=100, null=True, verbose_name='Объем двигателя (Снегоход или Квадроцикл)'),
        ),
        migrations.AddField(
            model_name='usacard',
            name='total',
            field=models.BooleanField(default=False, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='usacard',
            name='vehicle_type',
            field=models.CharField(choices=[('Седан', 'Седан'), ('Кроссовер', 'Кроссовер'), ('Внедорожник', 'Внедорожник'), ('Пикап', 'Пикап'), ('Габаритный авто', 'Габаритный авто'), ('Квадроциклы', 'Квадроциклы'), ('Мотоциклы', 'Мотоциклы'), ('Снегоходы', 'Снегоходы')], max_length=100, null=True, verbose_name='Тип ТС'),
        ),
        migrations.CreateModel(
            name='UsaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('auction_price', models.PositiveIntegerField(default=0, verbose_name='Аукционный сбор')),
                ('car_auct_price', models.PositiveIntegerField(default=0, verbose_name='Итого цена авто + аукционный сбор + комиссия')),
                ('payment_flag', models.BooleanField(default=False, verbose_name='Оплата на аукцион')),
                ('port', models.CharField(choices=[('Нью-Джерси', 'Нью-Джерси'), ('Джорджия', 'Джорджия'), ('Флорида', 'Флорида'), ('Техас', 'Техас'), ('Калифорния', 'Калифорния')], max_length=50, null=True, verbose_name='Порт отправки')),
                ('port_price', models.PositiveIntegerField(default=0, verbose_name='Доставка до порта')),
                ('moscow_price', models.PositiveIntegerField(default=0, verbose_name='Доставка до Москвы')),
                ('expenses_litva', models.PositiveIntegerField(default=0, verbose_name='Расходы в Литве')),
                ('delivery_price', models.PositiveIntegerField(default=0, verbose_name='Итого оплата доставки')),
                ('delivery_payment_flag', models.BooleanField(default=0, verbose_name='Оплата доставки')),
                ('extra_price', models.PositiveIntegerField(default=0, verbose_name='Иные платежи')),
                ('comment', models.CharField(blank=True, max_length=400, verbose_name='Комментарий')),
                ('tax_price', models.PositiveIntegerField(default=0, verbose_name='Таможенная пошлина')),
                ('tax_payment_flag', models.BooleanField(default=False, verbose_name='Оплата таможенной пошлины')),
                ('tax', models.PositiveIntegerField(default=0, verbose_name='Услуги Декларанта / таможни / СВХ')),
                ('tax_util', models.PositiveIntegerField(default=0, verbose_name='Утиль. сбор')),
                ('tax_rate', models.IntegerField(default=0, verbose_name='Установленная ставка на льготника')),
                ('tax_service', models.PositiveIntegerField(default=0, verbose_name='Наши услуги')),
                ('sbkts_epts', models.PositiveIntegerField(default=0, verbose_name='СБКТС + ЭПТС')),
                ('epsms_moto', models.PositiveIntegerField(default=0, verbose_name='ЭПСМС (Мото)')),
                ('excise', models.PositiveIntegerField(default=0, verbose_name='Акциз (Мото)')),
                ('penalty', models.PositiveIntegerField(default=0, verbose_name='Штрафы аукциона')),
                ('commission', models.PositiveIntegerField(default=0, verbose_name='Комиссия за перевод денег в США + % СВИФТ')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_site.usacard', verbose_name='Карточка США')),
            ],
        ),
        migrations.CreateModel(
            name='UsaTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_storage_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата доставки на склад')),
                ('container_load_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата загрузки в контейнер')),
                ('arrival_date_litva', models.DateField(default=django.utils.timezone.now, verbose_name='Дата прибытия в Литву')),
                ('open_container_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата открытия контейнера')),
                ('belarus_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата доставки в Беларусь')),
                ('moscow_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата доставки в Москву')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_site.usacard', verbose_name='Карточка США')),
            ],
        ),
    ]
