# Generated by Django 5.0.1 on 2024-02-04 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_site', '0017_alter_auctiondata_card_alter_usacard_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctiondata',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car_site.usacard', verbose_name='Карточка'),
        ),
        migrations.AlterField(
            model_name='usapayment',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car_site.usacard', verbose_name='Карточка США'),
        ),
        migrations.AlterField(
            model_name='usatracking',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car_site.usacard', verbose_name='Карточка США'),
        ),
    ]
