# Generated by Django 5.0.1 on 2024-02-04 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_site', '0018_alter_auctiondata_card_alter_usapayment_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usapayment',
            name='tax_sum',
            field=models.PositiveIntegerField(default=0, verbose_name='Итого ставка + пошлина'),
        ),
        migrations.AlterField(
            model_name='auctiondata',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='car_site.usaauction', verbose_name='Аукцион'),
        ),
        migrations.AlterField(
            model_name='auctiondata',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction_data', to='car_site.usacard', verbose_name='Карточка'),
        ),
        migrations.AlterField(
            model_name='auctiondata',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='car_site.usaplatform', verbose_name='Площадка'),
        ),
        migrations.AlterField(
            model_name='usacustomdocument',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='car_site.usacard', verbose_name='Таможенный документ'),
        ),
        migrations.AlterField(
            model_name='usaextralink',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='car_site.usacard', verbose_name='Карточка США'),
        ),
        migrations.AlterField(
            model_name='usapayment',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='car_site.usacard', verbose_name='Карточка США'),
        ),
        migrations.AlterField(
            model_name='usapaymentfile',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_files', to='car_site.usacard', verbose_name='Карточка США'),
        ),
        migrations.AlterField(
            model_name='usaphoto',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='car_site.usacard', verbose_name='Карточка США'),
        ),
        migrations.AlterField(
            model_name='usatracking',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='car_site.usacard', verbose_name='Карточка США'),
        ),
    ]
