# Generated by Django 5.0.1 on 2024-02-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_site', '0019_usapayment_tax_sum_alter_auctiondata_auction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctiondata',
            options={'verbose_name': 'Данные аукциона', 'verbose_name_plural': 'Данные аукциона'},
        ),
        migrations.AlterModelOptions(
            name='usapayment',
            options={'verbose_name': 'Платежи', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterModelOptions(
            name='usatracking',
            options={'verbose_name': 'Отслеживание', 'verbose_name_plural': 'Отслеживание'},
        ),
        migrations.AddField(
            model_name='auctiondata',
            name='lot_link',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ссылка на лот'),
        ),
    ]
