# Generated by Django 5.0.1 on 2024-02-05 20:40

import car_site.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_site', '0020_alter_auctiondata_options_alter_usapayment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='europephoto',
            options={'verbose_name': 'Фото осмотра', 'verbose_name_plural': 'Фото осмотра'},
        ),
        migrations.RemoveField(
            model_name='europecard',
            name='arrival_date_moscow',
        ),
        migrations.RemoveField(
            model_name='europecard',
            name='country',
        ),
        migrations.RemoveField(
            model_name='europecard',
            name='date_receipt_money',
        ),
        migrations.RemoveField(
            model_name='europecard',
            name='delivery_date_belarus',
        ),
        migrations.RemoveField(
            model_name='europecard',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='europecard',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='europecard',
            name='age',
            field=models.CharField(choices=[('0-3 года', '0-3 года'), ('3-5 лет', '3-5 лет'), ('5-7 лет', '5-7 лет')], max_length=100, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='europecard',
            name='capacity',
            field=models.CharField(choices=[('1.0', '1.0'), ('1.1', '1.1'), ('1.2', '1.2'), ('1.3', '1.3'), ('1.4', '1.4'), ('1.5', '1.5'), ('1.6', '1.6'), ('1.7', '1.9'), ('2.0', '2.0'), ('2.2', '2.2'), ('2.3', '2.3'), ('2.4', '2.4'), ('2.5', '2.5'), ('2.8', '2.8'), ('2.9', '2.9'), ('3.0', '3.0'), ('3.2', '3.2'), ('3.5', '3.5'), ('3.6', '3.6'), ('4.0', '4.0'), ('4.2', '4.2'), ('4.4', '4.4'), ('5.0', '5.0'), ('5.3', '5.3'), ('5.4', '5.4'), ('5.5', '5.5'), ('5.7', '5.7'), ('6.0', '6.0'), ('6.2', '6.2'), ('6.3', '6.3'), ('6.4', '6.4')], max_length=100, null=True, verbose_name='Объем'),
        ),
        migrations.AddField(
            model_name='europecard',
            name='cnt_auto',
            field=models.CharField(choices=[('1 авто', '1 авто'), ('2 и более', '2 и более')], max_length=10, null=True, verbose_name='Кол-во авто, купленных за год'),
        ),
        migrations.AddField(
            model_name='europecard',
            name='engine_type',
            field=models.CharField(choices=[('Бензин / Дизель / Гибрид', 'Бензин / Дизель / Гибрид'), ('Электро', 'Электро')], max_length=200, null=True, verbose_name='Тип двигателя'),
        ),
        migrations.AddField(
            model_name='europecard',
            name='massa',
            field=models.CharField(blank=True, choices=[('До  3,5 тонн', 'До  3,5 тонн'), ('Более 3,5 тонн', 'Более 3,5 тонн')], max_length=100, verbose_name='Масса техники (Пикап)'),
        ),
        migrations.AddField(
            model_name='europecard',
            name='motor_power',
            field=models.CharField(blank=True, choices=[('До 250-800 кубиков', 'До 250-800 кубиков'), ('Более 800 кубиков', 'Более 800 кубиков')], max_length=100, verbose_name='Объем двигателя (Мотоцикл)'),
        ),
        migrations.AddField(
            model_name='europecard',
            name='power',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Кол-во л. сил (Мотоцикл)'),
        ),
        migrations.AddField(
            model_name='europecard',
            name='price_brutto',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена Брутто (в евро)'),
        ),
        migrations.AddField(
            model_name='europecard',
            name='price_netto',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена Нетто (в евро)'),
        ),
        migrations.AddField(
            model_name='europecard',
            name='quadrupole',
            field=models.CharField(blank=True, choices=[('До 300 кубиков', 'До 300 кубиков'), ('Более 300 кубиков', 'Более 300 кубиков')], max_length=100, null=True, verbose_name='Объем двигателя (Снегоход или Квадроцикл)'),
        ),
        migrations.AddField(
            model_name='europecard',
            name='vehicle_type',
            field=models.CharField(choices=[('Авто', 'Авто'), ('Пикап', 'Пикап'), ('Квадроциклы', 'Квадроциклы'), ('Мотоциклы', 'Мотоциклы'), ('Снегоходы', 'Снегоходы')], max_length=100, null=True, verbose_name='Тип ТС'),
        ),
        migrations.AddField(
            model_name='europephoto',
            name='comment',
            field=models.CharField(default='Фото', max_length=200, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='europepaymentfile',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='car_site.europecard', verbose_name='Карточка Европы'),
        ),
        migrations.AlterField(
            model_name='europephoto',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='car_site.europecard', verbose_name='Карточка Европы'),
        ),
        migrations.CreateModel(
            name='EuroPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Комиссия за сопровождение сделки (в евро)')),
                ('auction_price', models.PositiveIntegerField(default=0, verbose_name='Итого авто +комиссия  (в евро)')),
                ('payment_flag', models.BooleanField(default=False, verbose_name='Оплата авто +комиссия')),
                ('inspection', models.PositiveIntegerField(default=0, verbose_name='Осмотр авто (в евро)')),
                ('expenses', models.PositiveIntegerField(default=0, verbose_name='Расходы по оплате в Европу (в евро)')),
                ('moscow_delivery_price', models.PositiveIntegerField(default=0, verbose_name='Доставка до Москвы (в евро)')),
                ('tax_price', models.PositiveIntegerField(default=0, verbose_name='Таможенная пошлина')),
                ('tax_flag', models.BooleanField(default=False, verbose_name='Оплата таможни')),
                ('tax', models.IntegerField(default=0, verbose_name='Установленная ставка')),
                ('tax_payment_flag', models.BooleanField(default=False, verbose_name='Итого таможня + ставка (в долларах) ')),
                ('tax_service', models.PositiveIntegerField(default=0, verbose_name='Услуги декларанта / Таможни / СВХ ( в рублях)')),
                ('tax_util', models.PositiveIntegerField(default=0, verbose_name='Утиль. сбор  в рублях')),
                ('tax_rate', models.IntegerField(default=0, verbose_name='Установленная ставка на льготника')),
                ('tax_sum', models.PositiveIntegerField(default=0, verbose_name='Итого ставка + пошлина')),
                ('our_service', models.PositiveIntegerField(default=0, verbose_name='Наши услуги в рублях')),
                ('sbkts_epts', models.PositiveIntegerField(default=0, verbose_name='СБКТС + ЭПТС в рублях')),
                ('epsms', models.PositiveIntegerField(default=0, verbose_name='ЭПСМС (Квадроциклы или Снегоходы)')),
                ('excise', models.PositiveIntegerField(default=0, verbose_name='Акциз (Мото)')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='car_site.europecard', verbose_name='Карточка Европы')),
            ],
            options={
                'verbose_name': 'Платежи',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='EuropeBelarusPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='Фото', max_length=200, verbose_name='Комментарий')),
                ('photo', models.ImageField(upload_to=car_site.models.get_timestamp_path, verbose_name='Фото')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belarus_photos', to='car_site.europecard', verbose_name='Карточка Европы')),
            ],
            options={
                'verbose_name': 'Фото из Беларуси',
                'verbose_name_plural': 'Фото из Беларуси',
            },
        ),
        migrations.CreateModel(
            name='EuropeExtraLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000, verbose_name='Ссылка')),
                ('name', models.CharField(default='Ссылка', max_length=300, verbose_name='Название')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='euro_links', to='car_site.usacard', verbose_name='Карточка Европы')),
            ],
            options={
                'verbose_name': 'Дополнительный ссылки',
                'verbose_name_plural': 'Дополнительные ссылки',
            },
        ),
        migrations.CreateModel(
            name='EuropeTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата оплаты')),
                ('money_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата поступления денег')),
                ('belarus_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата доставки в Беларусь')),
                ('moscow_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата доставки до Москвы')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='car_site.europecard', verbose_name='Карточка Европы')),
            ],
            options={
                'verbose_name': 'Отслеживание',
                'verbose_name_plural': 'Отслеживание',
            },
        ),
        migrations.CreateModel(
            name='EuroPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('Германия', 'Германия'), ('Голландия', 'Голландия'), ('Польша', 'Польша'), ('Литва', 'Литва'), ('Швейцария', 'Швейцария'), ('Италия', 'Италия'), ('Австрия', 'Австрия'), ('Чехия', 'Чехия'), ('Латвия', 'Латвия'), ('Эстония', 'Эстония')], max_length=50, verbose_name='Страна покупки')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата покупки')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='car_site.europecard', verbose_name='Карточка Европы')),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки',
            },
        ),
    ]
