# Generated by Django 5.0.1 on 2024-02-05 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_site', '0021_alter_europephoto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='europeextralink',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='euro_links', to='car_site.europecard', verbose_name='Карточка Европы'),
        ),
    ]
