# Generated by Django 5.0.1 on 2024-02-05 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_site', '0022_alter_europeextralink_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='europayment',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='car_site.europecard', verbose_name='Карточка Европы'),
        ),
        migrations.AlterField(
            model_name='europetracking',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='car_site.europecard', verbose_name='Карточка Европы'),
        ),
        migrations.AlterField(
            model_name='europlatform',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='car_site.europecard', verbose_name='Карточка Европы'),
        ),
    ]
