# Generated by Django 5.0.1 on 2024-02-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_site', '0024_remove_europayment_tax_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='europayment',
            name='tax_payment',
            field=models.BooleanField(default=False, verbose_name='Итого таможня + ставка (в долларах) '),
        ),
        migrations.AlterField(
            model_name='europayment',
            name='tax_payment_flag',
            field=models.BooleanField(default=False, verbose_name='Оплачено таможня + ставка '),
        ),
    ]
