# Generated by Django 5.0.1 on 2024-02-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_site', '0025_europayment_tax_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='europayment',
            name='tax_payment',
            field=models.PositiveIntegerField(default=False, verbose_name='Итого таможня + ставка (в долларах) '),
        ),
    ]
