# Generated by Django 5.0.1 on 2024-02-06 11:32

import car_site.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_site', '0026_alter_europayment_tax_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='koreaphoto',
            options={'verbose_name': 'Фотография c Владивостока', 'verbose_name_plural': 'Фотографии c Владивостока'},
        ),
        migrations.RemoveField(
            model_name='koreacard',
            name='arrival_date_vladivostok',
        ),
        migrations.RemoveField(
            model_name='koreacard',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='koreacard',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='koreacard',
            name='age',
            field=models.CharField(choices=[('0-3 года', '0-3 года'), ('3-5 лет', '3-5 лет'), ('5-7 лет', '5-7 лет')], max_length=100, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='koreacard',
            name='capacity',
            field=models.CharField(choices=[('1.0', '1.0'), ('1.1', '1.1'), ('1.2', '1.2'), ('1.3', '1.3'), ('1.4', '1.4'), ('1.5', '1.5'), ('1.6', '1.6'), ('1.7', '1.9'), ('2.0', '2.0'), ('2.2', '2.2'), ('2.3', '2.3'), ('2.4', '2.4'), ('2.5', '2.5'), ('2.8', '2.8'), ('2.9', '2.9'), ('3.0', '3.0'), ('3.2', '3.2'), ('3.5', '3.5'), ('3.6', '3.6'), ('4.0', '4.0'), ('4.2', '4.2'), ('4.4', '4.4'), ('5.0', '5.0'), ('5.3', '5.3'), ('5.4', '5.4'), ('5.5', '5.5'), ('5.7', '5.7'), ('6.0', '6.0'), ('6.2', '6.2'), ('6.3', '6.3'), ('6.4', '6.4')], max_length=100, null=True, verbose_name='Объем'),
        ),
        migrations.AddField(
            model_name='koreacard',
            name='cnt_auto',
            field=models.CharField(choices=[('1 авто', '1 авто'), ('2 и более', '2 и более')], max_length=10, null=True, verbose_name='Кол-во авто, купленных за год'),
        ),
        migrations.AddField(
            model_name='koreacard',
            name='engine_type',
            field=models.CharField(choices=[('Бензин / Дизель / Гибрид', 'Бензин / Дизель / Гибрид'), ('Электро', 'Электро')], max_length=200, null=True, verbose_name='Тип двигателя'),
        ),
        migrations.AddField(
            model_name='koreacard',
            name='final_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата прибытия в конечный пункт'),
        ),
        migrations.AddField(
            model_name='koreacard',
            name='massa',
            field=models.CharField(blank=True, choices=[('До  3,5 тонн', 'До  3,5 тонн'), ('Более 3,5 тонн', 'Более 3,5 тонн')], max_length=100, verbose_name='Масса техники (Пикап)'),
        ),
        migrations.AddField(
            model_name='koreacard',
            name='money_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата поступления денег'),
        ),
        migrations.AddField(
            model_name='koreacard',
            name='motor_power',
            field=models.CharField(blank=True, choices=[('До 250-800 кубиков', 'До 250-800 кубиков'), ('Более 800 кубиков', 'Более 800 кубиков')], max_length=100, verbose_name='Объем двигателя (Мотоцикл)'),
        ),
        migrations.AddField(
            model_name='koreacard',
            name='pay_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата покупки'),
        ),
        migrations.AddField(
            model_name='koreacard',
            name='power',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Кол-во л. сил (Мотоцикл)'),
        ),
        migrations.AddField(
            model_name='koreacard',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость авто (в долларах)'),
        ),
        migrations.AddField(
            model_name='koreacard',
            name='quadrupole',
            field=models.CharField(blank=True, choices=[('До 300 кубиков', 'До 300 кубиков'), ('Более 300 кубиков', 'Более 300 кубиков')], max_length=100, null=True, verbose_name='Объем двигателя (Снегоход или Квадроцикл)'),
        ),
        migrations.AddField(
            model_name='koreacard',
            name='vehicle_type',
            field=models.CharField(choices=[('Авто', 'Авто'), ('Пикап', 'Пикап'), ('Квадроциклы', 'Квадроциклы'), ('Мотоциклы', 'Мотоциклы'), ('Снегоходы', 'Снегоходы')], max_length=100, null=True, verbose_name='Тип ТС'),
        ),
        migrations.AddField(
            model_name='koreacard',
            name='vladivostok_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата прибытия во Владивосток'),
        ),
        migrations.AddField(
            model_name='koreaphoto',
            name='comment',
            field=models.CharField(max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='europebelarusphoto',
            name='comment',
            field=models.CharField(default='Фото', max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='europephoto',
            name='comment',
            field=models.CharField(default='Фото', max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='koreacard',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='usaphoto',
            name='comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='KoreaCustomDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=car_site.models.get_file_path, verbose_name='Файл')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korea_documents', to='car_site.koreacard', verbose_name='Таможенный документ')),
            ],
            options={
                'verbose_name': 'Таможенный документ',
                'verbose_name_plural': 'Таможенные документы',
            },
        ),
        migrations.CreateModel(
            name='KoreaExtraLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000, verbose_name='Ссылка')),
                ('name', models.CharField(default='Ссылка', max_length=300, verbose_name='Название')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korea_links', to='car_site.koreacard', verbose_name='Карточка Европы')),
            ],
            options={
                'verbose_name': 'Дополнительный ссылки',
                'verbose_name_plural': 'Дополнительные ссылки',
            },
        ),
        migrations.CreateModel(
            name='KoreaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_price', models.PositiveIntegerField(default=0, verbose_name='Стоимость авто (в долларах)')),
                ('export', models.PositiveIntegerField(default=0, verbose_name='Экспортные документы и доставка до ВДК (в долларах)')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='Итого авто + экспортные документы (в долларах)')),
                ('payment_flag', models.BooleanField(default=False, verbose_name='Оплата авто + экспортные документы')),
                ('delivery_price', models.PositiveIntegerField(default=0, verbose_name='Доставка из ВДК до конечного пункта в рублях')),
                ('tax_price', models.PositiveIntegerField(default=0, verbose_name='Таможенная пошлина (в долларах)')),
                ('tax_flag', models.BooleanField(default=False, verbose_name='Оплата таможни')),
                ('tax', models.IntegerField(default=0, verbose_name='Установленная ставка (в долларах)')),
                ('tax_payment', models.PositiveIntegerField(default=False, verbose_name='Итого таможня + ставка (в долларах) ')),
                ('tax_payment_flag', models.BooleanField(default=False, verbose_name='Оплачено таможня + ставка ')),
                ('tax_service', models.PositiveIntegerField(default=0, verbose_name='Услуги декларанта / Таможни / СВХ ( в рублях)')),
                ('tax_util', models.PositiveIntegerField(default=0, verbose_name='Утиль. сбор  в рублях')),
                ('our_service', models.PositiveIntegerField(default=0, verbose_name='Наши услуги в рублях')),
                ('sbkts_epts', models.PositiveIntegerField(default=0, verbose_name='СБКТС + ЭПТС в рублях')),
                ('epsms', models.PositiveIntegerField(default=0, verbose_name='ЭПСМС (Квадроциклы или Снегоходы)')),
                ('excise', models.PositiveIntegerField(default=0, verbose_name='Акциз (Мото)')),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='korea_payment', to='car_site.europecard', verbose_name='Карточка Европы')),
            ],
            options={
                'verbose_name': 'Платежи',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='KoreaTKPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, null=True, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to=car_site.models.get_timestamp_path, verbose_name='Фото')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_site.koreacard', verbose_name='Карточка Южной Кореи')),
            ],
            options={
                'verbose_name': 'Фотография c доставки в ТК',
                'verbose_name_plural': 'Фотографии с доставки в ТК',
            },
        ),
    ]
