# Generated by Django 5.0.1 on 2024-02-06 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_site', '0027_alter_koreaphoto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koreapayment',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='korea_payment', to='car_site.koreacard', verbose_name='Карточка Европы'),
        ),
    ]
