# Generated by Django 5.0.1 on 2024-02-06 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_site', '0028_alter_koreapayment_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='koreacard',
            name='money_date',
        ),
    ]
