# Generated by Django 5.0.1 on 2024-02-06 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_site', '0029_remove_koreacard_money_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koreapaymentfile',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korea_files', to='car_site.koreacard', verbose_name='Карточка Южной Кореи'),
        ),
        migrations.AlterField(
            model_name='koreaphoto',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korea_photo', to='car_site.koreacard', verbose_name='Карточка Южной Кореи'),
        ),
        migrations.AlterField(
            model_name='koreatkphoto',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korea_tk_photo', to='car_site.koreacard', verbose_name='Карточка Южной Кореи'),
        ),
    ]
