# Generated by Django 5.0.1 on 2025-04-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_site', '0031_alter_usaphoto_options_remove_auctiondata_lot_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usatracking',
            name='arrival_date_litva',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата прибытия в Турцию'),
        ),
    ]
