# Generated by Django 5.0.1 on 2025-04-09 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
        ('car_site', '0031_alter_usaphoto_options_remove_auctiondata_lot_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctiondata',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_auctions', to='calculator.auction', verbose_name='Аукцион'),
        ),
        migrations.RemoveField(
            model_name='usaplatform',
            name='auction',
        ),
        migrations.AlterField(
            model_name='usaallowedcombination',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.auction', verbose_name='Аукцион'),
        ),
        migrations.AlterField(
            model_name='usaallowedcombination',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.location', verbose_name='Площадка'),
        ),
        migrations.AlterField(
            model_name='auctiondata',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_platforms', to='calculator.location', verbose_name='Площадка'),
        ),
        migrations.DeleteModel(
            name='UsaAuction',
        ),
        migrations.DeleteModel(
            name='UsaPlatform',
        ),
    ]
