# Generated by Django 4.2.7 on 2024-11-26 22:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USD_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Курс USD')),
                ('USD_source', models.CharField(choices=[('manual', 'Ручной ввод'), ('cbr', 'ЦБ РФ'), ('garantex', 'Garantex')], default='manual', max_length=10, verbose_name='Источник USD')),
                ('EUR_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Курс EUR')),
                ('EUR_source', models.CharField(choices=[('manual', 'Ручной ввод'), ('cbr', 'ЦБ РФ')], default='manual', max_length=10, verbose_name='Источник EUR')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
            },
        ),
    ]
